# name: Test workflow

# on:
#   pull_request:
#     branches:
#       - develop
#       - staging

# jobs:
#   test:
   
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v1

#       - name: Use Node.js 21.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: 21.x

#       - name: 🧰 Install Deps
#         run: npm install

#       - name: Run Build
#         run: npm run build
    
#       - name: Start the server
#         env:
#           MONGODB_URI: mongodb+srv://dbUser:rootroot@googlebooks.7s2ke.mongodb.net/?retryWrites=true&w=majority&appName=GoogleBooks
#         run: |
#           npm run start &
#           npx wait-on http://localhost:3001 

#       - name: Run Tests
#         run: npm run test-component

name: Checking Tests

on:
  pull_request:
    branches:
    - develop

jobs:
  test:
    name: Checking Tests
    runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          component: true
          